export interface Book {
  slug: string
  title: string
  author: string
  genre: 'Epic' | 'Liric' | 'Dramă' | 'Populare'
  description: string
  emailCount: number
  readingTime: number
  coverColor: string
  coverImage?: string
  year?: string
  themes?: string[]
  featured?: boolean
}

export const allBooks: Book[] = [
  // EPIC (Proză)
  {
    slug: 'ion-liviu-rebreanu',
    title: 'Ion',
    author: 'Liviu Rebreanu',
    genre: 'Epic',
    description: 'Romanul lui Ion, țăranul obsedat de pământ.',
    emailCount: 112,
    readingTime: 10,
    coverColor: '#5D4E37',
    coverImage: '/covers/ion.png',
    year: '1920',
    featured: true,
  },
  {
    slug: 'ultima-noapte-camil-petrescu',
    title: 'Ultima noapte de dragoste, întâia noapte de război',
    author: 'Camil Petrescu',
    genre: 'Epic',
    description: 'Romanul geloziei și al experienței războiului.',
    emailCount: 68,
    readingTime: 10,
    coverColor: '#4A3728',
    coverImage: '/covers/ultima-noapte.jpg',
    year: '1930',
    featured: true,
  },
  {
    slug: 'morometii-marin-preda',
    title: 'Moromeții I',
    author: 'Marin Preda',
    genre: 'Epic',
    description: 'Saga familiei Moromete în perioada interbelică.',
    emailCount: 101,
    readingTime: 10,
    coverColor: '#6B5344',
    coverImage: '/covers/morometii.png',
    year: '1955',
    featured: true,
  },
  {
    slug: 'enigma-otiliei-george-calinescu',
    title: 'Enigma Otiliei',
    author: 'George Călinescu',
    genre: 'Epic',
    description: 'Romanul familiei Tulea și al enigmaticei Otilia.',
    emailCount: 125,
    readingTime: 10,
    coverColor: '#8B4513',
    coverImage: '/covers/enigma-otiliei.png',
    year: '1938',
    featured: true,
  },
  {
    slug: 'baltagul-mihail-sadoveanu',
    title: 'Baltagul',
    author: 'Mihail Sadoveanu',
    genre: 'Epic',
    description: 'Călătoria Vitoriei Lipan în căutarea soțului dispărut.',
    emailCount: 29,
    readingTime: 10,
    coverColor: '#2E5A4C',
    coverImage: '/covers/baltagul.png',
    year: '1930',
    featured: true,
  },
  {
    slug: 'moara-cu-noroc-ioan-slavici',
    title: 'Moara cu noroc',
    author: 'Ioan Slavici',
    genre: 'Epic',
    description: 'Nuvela despre decăderea morală a lui Ghiță.',
    emailCount: 26,
    readingTime: 8,
    coverColor: '#3D3D3D',
    coverImage: '/covers/moara-cu-noroc.png',
    year: '1881',
    featured: true,
  },
  {
    slug: 'alexandru-lapusneanu',
    title: 'Alexandru Lăpușneanu',
    author: 'Costache Negruzzi',
    genre: 'Epic',
    description: 'Nuvela istorică despre domnitorul Lăpușneanu.',
    emailCount: 5,
    readingTime: 6,
    coverColor: '#4A4A4A',
    coverImage: '/covers/alexandru-lapusneanu.png',
    year: '1840',
    featured: false,
  },
  {
    slug: 'suflete-tari-camil-petrescu',
    title: 'Suflete tari',
    author: 'Camil Petrescu',
    genre: 'Dramă',
    description: 'Drama idealurilor și a compromisurilor.',
    emailCount: 30,
    readingTime: 8,
    coverColor: '#5A4A3A',
    coverImage: '/covers/suflete-tari.png',
    year: '1938',
    featured: false,
  },
  {
    slug: 'jocul-ielelor',
    title: 'Jocul ielelor',
    author: 'Camil Petrescu',
    genre: 'Dramă',
    description: 'Drama autenticității și corupției.',
    emailCount: 30,
    readingTime: 8,
    coverColor: '#4A5A3A',
    coverImage: '/covers/jocul-ielelor.png',
    year: '1919',
    featured: false,
  },
  {
    slug: 'iona-marin-sorescu',
    title: 'Iona',
    author: 'Marin Sorescu',
    genre: 'Dramă',
    description: 'Drama existențială a singurătății.',
    emailCount: 6,
    readingTime: 6,
    coverColor: '#3A4A5A',
    coverImage: '/covers/iona.png',
    year: '1968',
    featured: false,
  },
  {
    slug: 'cel-mai-iubit-marin-preda',
    title: 'Cel mai iubit dintre pământeni',
    author: 'Marin Preda',
    genre: 'Epic',
    description: 'Romanul lui Victor Petrini în epoca comunistă.',
    emailCount: 101,
    readingTime: 10,
    coverColor: '#5A5A5A',
    coverImage: '/covers/cel-mai-iubit.png',
    year: '1980',
    featured: false,
  },
  {
    slug: 'maitreyi-mircea-eliade',
    title: 'Maitreyi',
    author: 'Mircea Eliade',
    genre: 'Epic',
    description: 'Romanul iubirii exotice în India.',
    emailCount: 41,
    readingTime: 8,
    coverColor: '#8B6914',
    coverImage: '/covers/maitreyi.png',
    year: '1933',
    featured: true,
  },
  {
    slug: 'patul-lui-procust',
    title: 'Patul lui Procust',
    author: 'Camil Petrescu',
    genre: 'Epic',
    description: 'Romanul autenticității și al conștiinței.',
    emailCount: 85,
    readingTime: 10,
    coverColor: '#4A4A6A',
    coverImage: '/covers/patul-lui-procust.png',
    year: '1933',
    featured: false,
  },

  // POPULARE
  {
    slug: 'harap-alb-ion-creanga',
    title: 'Harap-Alb',
    author: 'Ion Creangă',
    genre: 'Populare',
    description: 'Basmul inițierii și al încercărilor eroului.',
    emailCount: 21,
    readingTime: 8,
    coverColor: '#2E7D32',
    coverImage: '/covers/harap-alb.png',
    year: '1877',
    featured: true,
  },
  {
    slug: 'mesterul-manole',
    title: 'Meșterul Manole',
    author: 'Lucian Blaga',
    genre: 'Dramă',
    description: 'Drama creației și sacrificiului suprem.',
    emailCount: 30,
    readingTime: 8,
    coverColor: '#5D4037',
    coverImage: '/covers/mesterul-manole.png',
    year: '1927',
    featured: false,
  },

  // LIRIC
  {
    slug: 'luceafarul-mihai-eminescu',
    title: 'Luceafărul',
    author: 'Mihai Eminescu',
    genre: 'Liric',
    description: 'Poemul geniului și al iubirii imposibile.',
    emailCount: 4,
    readingTime: 8,
    coverColor: '#1A237E',
    coverImage: '/covers/luceafarul.png',
    year: '1883',
    featured: true,
  },
  {
    slug: 'scrisoarea-i',
    title: 'Scrisoarea I',
    author: 'Mihai Eminescu',
    genre: 'Liric',
    description: 'Meditația filozofică asupra cosmosului.',
    emailCount: 1,
    readingTime: 8,
    coverColor: '#283593',
    coverImage: '/covers/scrisoarea-i.png',
    year: '1881',
    featured: false,
  },
  {
    slug: 'scrisoarea-iii',
    title: 'Scrisoarea III',
    author: 'Mihai Eminescu',
    genre: 'Liric',
    description: 'Poemul istoric și patriotic.',
    emailCount: 2,
    readingTime: 10,
    coverColor: '#B71C1C',
    coverImage: '/covers/scrisoarea-iii.png',
    year: '1881',
    featured: true,
  },
  {
    slug: 'dorinta-mihai-eminescu',
    title: 'Dorință',
    author: 'Mihai Eminescu',
    genre: 'Liric',
    description: 'Poezia iubirii romantice.',
    emailCount: 30,
    readingTime: 5,
    coverColor: '#C62828',
    coverImage: '/covers/dorinta.png',
    year: '1876',
    featured: false,
  },
  {
    slug: 'floare-albastra-mihai-eminescu',
    title: 'Floare albastră',
    author: 'Mihai Eminescu',
    genre: 'Liric',
    description: 'Idila romantică a poetului.',
    emailCount: 1,
    readingTime: 5,
    coverColor: '#1565C0',
    coverImage: '/covers/floare-albastra.png',
    year: '1873',
    featured: false,
  },
  {
    slug: 'mai-am-un-singur-dor',
    title: 'Mai am un singur dor',
    author: 'Mihai Eminescu',
    genre: 'Liric',
    description: 'Testamentul poetic al lui Eminescu.',
    emailCount: 30,
    readingTime: 5,
    coverColor: '#0D47A1',
    coverImage: '/covers/mai-am-un-singur-dor.png',
    year: '1883',
    featured: false,
  },
  {
    slug: 'testament-tudor-arghezi',
    title: 'Testament',
    author: 'Tudor Arghezi',
    genre: 'Liric',
    description: 'Arta poetică argheziană.',
    emailCount: 1,
    readingTime: 5,
    coverColor: '#455A64',
    coverImage: '/covers/testament.png',
    year: '1927',
    featured: true,
  },
  {
    slug: 'flori-de-mucigai-tudor-arghezi',
    title: 'Flori de mucigai',
    author: 'Tudor Arghezi',
    genre: 'Liric',
    description: 'Ciclul poeziilor din închisoare.',
    emailCount: 6,
    readingTime: 8,
    coverColor: '#37474F',
    coverImage: '/covers/flori-de-mucigai.png',
    year: '1931',
    featured: false,
  },
  {
    slug: 'eu-nu-strivesc-corola-lucian-blaga',
    title: 'Eu nu strivesc corola de minuni a lumii',
    author: 'Lucian Blaga',
    genre: 'Liric',
    description: 'Arta poetică blagiană.',
    emailCount: 2,
    readingTime: 5,
    coverColor: '#6A1B9A',
    coverImage: '/covers/eu-nu-strivesc.png',
    year: '1919',
    featured: true,
  },
  {
    slug: 'plumb-george-bacovia',
    title: 'Plumb',
    author: 'George Bacovia',
    genre: 'Liric',
    description: 'Poezia simbolistă a singurătății.',
    emailCount: 2,
    readingTime: 5,
    coverColor: '#424242',
    coverImage: '/covers/plumb.png',
    year: '1916',
    featured: true,
  },
  {
    slug: 'lacustra-george-bacovia',
    title: 'Lacustră',
    author: 'George Bacovia',
    genre: 'Liric',
    description: 'Viziunea apocaliptică a orașului.',
    emailCount: 2,
    readingTime: 5,
    coverColor: '#263238',
    coverImage: '/covers/lacustra.png',
    year: '1916',
    featured: false,
  },
  {
    slug: 'riga-crypto-ion-barbu',
    title: 'Riga Crypto și lapona Enigel',
    author: 'Ion Barbu',
    genre: 'Liric',
    description: 'Balada hermetică a iubirii imposibile.',
    emailCount: 3,
    readingTime: 8,
    coverColor: '#00695C',
    coverImage: '/covers/riga-crypto.png',
    year: '1930',
    featured: true,
  },

  // DRAMĂ
  {
    slug: 'o-scrisoare-pierduta-caragiale',
    title: 'O scrisoare pierdută',
    author: 'I.L. Caragiale',
    genre: 'Dramă',
    description: 'Comedia electorală a lui Caragiale.',
    emailCount: 12,
    readingTime: 10,
    coverColor: '#E65100',
    coverImage: '/covers/o-scrisoare-pierduta.png',
    year: '1884',
    featured: true,
  },
]

// Funcții helper
export function getBookBySlug(slug: string): Book | undefined {
  return allBooks.find(book => book.slug === slug)
}

export function getBooksByGenre(genre: Book['genre']): Book[] {
  return allBooks.filter(book => book.genre === genre)
}

export function getBooksByAuthor(author: string): Book[] {
  return allBooks.filter(book => book.author === author)
}

export function getFeaturedBooks(): Book[] {
  return allBooks.filter(book => book.featured)
}

// Genuri pentru filtrare
export const genres: Book['genre'][] = ['Epic', 'Liric', 'Dramă', 'Populare']

// Autori pentru filtrare
export const authors = Array.from(new Set(allBooks.map(book => book.author)))
